### ISSUE TITLE
The single image edit code does not seem to edit the round cake to square.

### ISSUE THREAD

**Issue by RahulSajnani** [cure-lab/DirectInversion#2]
Hi

When I run the single image directinversion+p2p edit code it does not change the round cake to a square one. It gives the below output. Also, what are blend words exactly? Can you give me an idea of what words to blend so that I can use custom images and prompts?

![directinversion+p2p](https://github.com/cure-lab/DirectInversion/assets/47087620/c51071fb-0a9d-464b-a503-b67e565c414a)

**Comment by juxuan27** [comment]
Hi, @RahulSajnani. Thank you for your focus. Please check if you have used the correct diffuser version as listed in readme.

**Comment by RahulSajnani** [comment]
Hi @juxuan27! Thanks for getting back. I ran the single image p2p script and my environment is built using the p2p_requirements.txt file. My diffusers version is 0.10.0

**Comment by juxuan27** [comment]
The blended word is the target object that needed to be edit, you could use "cake cake" in this example (as we have given in .ipynb). Would you please give me more detailed usage in your code so that maybe I could find why this happen?

**Comment by RahulSajnani** [comment]
Hi @juxuan27. Your cake example is not working for me (single image p2p). I am using the diffusers 0.10.0

**Comment by juxuan27** [comment]
Yes, I understand. But would you please give me details on how you run it? For example, the exact python file and the corresponding running scripts such as python xxx.py xxx.

**Comment by RahulSajnani** [comment]
Hi @juxuan27. Thanks for getting back.
I run it as follows:
```
python -u run_editing_p2p_one_image.py --image_path scripts/example_cake.jpg --original_prompt "a round cake with orange frosting on a wooden plate" --editing_prompt "a square cake with orange frosting on a wooden plate" --blended_word "cake cake" --output_path "directinversion+p2p.jpg" "ddim+p2p.jpg" --edit_method_list "directinversion+p2p" "ddim+p2p"
```

I followed the following instructions for creating my conda environment:
```
conda create -n p2p python=3.9 -y
conda activate p2p
conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch
pip3 install -r environment/p2p_requirements.txt
```

**Comment by juxuan27** [comment]
Sorry for the late reply. It's quite weird... I run the same command as you listed and get correct editing results.
Would you please try "null-text-inversion+p2p" and see if it can work? If not, I think there is something wrong with your local environment.

**Comment by zhaocong1992** [comment]
same probelm.

**Comment by juxuan27** [comment]
Hi, @zhaocong1992 !
Would you please try [this](https://github.com/cure-lab/DirectInversion/issues/2#issuecomment-1763332964) and give me some feedback on this issue? Hope we could solve this problem together because everything works fine on my cluster and I really don't know what's going on hhh.

**Comment by ezgiekiz** [comment]
I followed the same setup listed above and [run_editing_p2p_one_image.py](https://github.com/cure-lab/DirectInversion/blob/main/run_editing_p2p_one_image.py) gives the unedited results as @RahulSajnani shared. However, running  [run_editing_p2p_one_image.ipynb](https://github.com/cure-lab/DirectInversion/blob/main/run_editing_p2p_one_image.ipynb) gives the correct results. You may consider to check the difference between them. Thank you.

**Comment by juxuan27** [comment]
Hi, @ezgiekiz ! Thank you for your help. I will check the reason causing this problem and fix the bug.

**Comment by juxuan27** [comment]
The bug is fixed in [this commit](https://github.com/cure-lab/DirectInversion/commit/d1b9359603e7127a7d6c503d3104e9e0e872ac6c). Thank you for all your help!!
