### ISSUE TITLE
Some question about environment

### ISSUE THREAD

**Issue by wangzhen-ing** [cure-lab/DirectInversion#4]
Hello, I would like to ask, if I want to run run_editing_pnp.py, do I need to configure the environment first according to the official [plug-and-play](https://github.com/MichalGeyer/plug-and-play) environment, and then install environment/pnp_requirements.txt in your code?

**Comment by juxuan27** [comment]
Hi, in fact, both ways are fine. You can setup the environment with either the official [plug-and-play](https://github.com/MichalGeyer/plug-and-play) environment or environment/pnp_requirements.txt. We just give out the environment/pnp_requirements.txt for ease of use. The code in our repo are basically the same as the official plug-and-play thus have same environment requirements.

**Comment by wangzhen-ing** [comment]
> Hi, in fact, both ways are fine. You can setup the environment with either the official [plug-and-play](https://github.com/MichalGeyer/plug-and-play) environment or environment/pnp_requirements.txt. We just give out the environment/pnp_requirements.txt for ease of use. The code in our repo are basically the same as the official plug-and-play thus have same environment requirements.

thank you very much for your answer!
