### ISSUE TITLE
question about benchmark

### ISSUE THREAD

**Issue by wangzhen-ing** [cure-lab/DirectInversion#5]
hello, thanks for your work.
Can you share some code or more details for building benchmark?  For example, how to generate captions in batches through blip2, and how to match text and images to generate JSON files? and how to compute the metrics in the table of COMPARISON WITH INVERSION-BASED EDITING, is it the average of every image in the benchmark dataset for every methods.

**Comment by juxuan27** [comment]
Hi, @wangzhen-ing . Unfortunately, we will not share the scripts for generating the benchmark. But you can find how to use blip2 to caption images in [huggingface](https://huggingface.co/docs/transformers/v4.28.1/model_doc/blip-2#transformers.Blip2Model). For the metrics calculation, we have already release [here](https://github.com/cure-lab/DirectInversion/tree/main/evaluation). You can refer to readme for more usage.

**Comment by wangzhen-ing** [comment]
> Hi, @wangzhen-ing . Unfortunately, we will not share the scripts for generating the benchmark. But you can find how to use blip2 to caption images in [huggingface](https://huggingface.co/docs/transformers/v4.28.1/model_doc/blip-2#transformers.Blip2Model). For the metrics calculation, we have already release [here](https://github.com/cure-lab/DirectInversion/tree/main/evaluation). You can refer to readme for more usage.

OK, thank you for your reply！
