### ISSUE TITLE
OOM Error

### ISSUE THREAD

**Issue by alinrdinn** [cure-lab/DirectInversion#7]
I try your code but it seems i got OOM error. At first, the code download so many models (is it necessary to download those all and use those all at a time?) I just only test the code for only one image. Any advice? Thx

**Comment by juxuan27** [comment]
May I know the script you used for testing?

**Comment by alinrdinn** [comment]
The IPYNB file. I only run it.

**Comment by alinrdinn** [comment]
Well... It seems (using the IPYNB file) your code must download all models (32 and 16 precision bits). But I found it that your code can use the 16-bit (which will have memory and GPU significant impact if you refactor the code). 

I also want to ask whether your code can be used for other models other than the stable diffusion 1.4? Thx  @juxuan27

**Comment by juxuan27** [comment]
- For the first question. I think the downloading process is auto-completed by diffusers. If you do not necessarily need a high precision, using 16-bit can save GPU memory for you and might solve OOM error.
- For the second question. Yes, the code should be used for stable diffusion v1.5 and models tuned from stable diffusion v1.4 and v1.5.
